### ISSUE TITLE
Proxy Failed

### ISSUE THREAD

**Issue by atilladeniz** [Oreoezi/behance-like-bot#3]
It always comes a lot of number and [!]Proxy Failes 302

**Comment by Oreoezi** [comment]
Hi, did you install the packages?

**Comment by atilladeniz** [comment]
yees I install the packages

**Comment by atilladeniz** [comment]
NPM install and runs but i think it not catch the proxy list that i already order from webshare

**Comment by Oreoezi** [comment]
> NPM install and runs but i think it not catch the proxy list that i already order from webshare

make sure they are socks4 proxies

**Comment by atilladeniz** [comment]
ahh okay HTTP not allowed?

**Comment by atilladeniz** [comment]
Socks5 also allows?

**Comment by Oreoezi** [comment]
> ahh okay HTTP not allowed?

change bot.js for that

**Comment by atilladeniz** [comment]
it not works with http.. 

const puppeteer = require("puppeteer");
const button_path = "div[data-adobe-analytics='AppreciateClick']";
const isClicked = "div[data-adobe-analytics='UnappreciateClick']";
process.on("uncaughtException", () => {
    process.exit(-1);
});
process.on("unhandledRejection", () => {
    process.exit(-1);
});
async function main() {
    const browser = await puppeteer.launch({
        args: [ "--proxy-server=http://" + process.argv[2],
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-accelerated-2d-canvas",
        "--no-first-run",
        "--no-zygote",
        "--disable-gpu"],
        defaultViewport: {
            width: 1800 + Math.floor(Math.random() * 100),
            height: 900 + Math.floor(Math.random() * 100),
            deviceScaleFactor: 1,
            hasTouch: false,
            isLandscape: false,
            isMobile: false
        }
    });
    const page = await browser.newPage();
    await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");
    await page.setRequestInterception(true);
    page.on("request", req => {
        if (req.resourceType() == "image" || 
        req.resourceType() == "stylesheet" ||
        req.resourceType() == "font") return req.abort();
        req.continue();
    });
    await page.goto(process.argv[3]);
    await page.waitForSelector(button_path);
    await new Promise((res,rej) => setTimeout(res, 1000));
    await page.click(button_path);
    await page.waitForSelector(isClicked);
    await page.close();
    await browser.close();
}
main();

**Comment by atilladeniz** [comment]
{
    "project_page": "https://www.behance.net/gallery/136920549/WOODFRUT",
    "like_count": 15,
    "downloadProxies": false,
    "instances": 10
}

**Comment by Oreoezi** [comment]
> it not works with http..
> 
> const puppeteer = require("puppeteer"); const button_path = "div[data-adobe-analytics='AppreciateClick']"; const isClicked = "div[data-adobe-analytics='UnappreciateClick']"; process.on("uncaughtException", () => { process.exit(-1); }); process.on("unhandledRejection", () => { process.exit(-1); }); async function main() { const browser = await puppeteer.launch({ args: [ "--proxy-server=http://" + process.argv[2], "--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-accelerated-2d-canvas", "--no-first-run", "--no-zygote", "--disable-gpu"], defaultViewport: { width: 1800 + Math.floor(Math.random() * 100), height: 900 + Math.floor(Math.random() * 100), deviceScaleFactor: 1, hasTouch: false, isLandscape: false, isMobile: false } }); const page = await browser.newPage(); await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"); await page.setRequestInterception(true); page.on("request", req => { if (req.resourceType() == "image" || req.resourceType() == "stylesheet" || req.resourceType() == "font") return req.abort(); req.continue(); }); await page.goto(process.argv[3]); await page.waitForSelector(button_path); await new Promise((res,rej) => setTimeout(res, 1000)); await page.click(button_path); await page.waitForSelector(isClicked); await page.close(); await browser.close(); } main();

sounds about right
Change `args: [ "--proxy-server=socks4://" + process.argv[2],` to `args: [ "--proxy-server=http://" + process.argv[2],`
